### ISSUE TITLE
OBS Multiplatform version

### ISSUE THREAD

**Issue by shughes-uk** [bilhamil/OBSRemote#10]
OBS Multiplatform is nearing feature parity with OBS main which will be deprecated. Would be worth updating this plugin to work with multiplatform.

**Comment by Ushantilp** [comment]
Support for the OBS Multiplatform would be great, would like to switch but without OBS remote makes it easy for me currently no sense, besides me OBS Multiplatform like much better
I hope it is planned to adapt OBS Remote?
Information would be great

Ushantilp

**Comment by coreyog** [comment]
+1 for this

**Comment by macharborguy** [comment]
I too am awaiting a Multiplatform update to OBSRemote.  It is such an invaluable tool for our stream, but the fact that it has yet to be updated, even in a pre-release form for OBS MultiPlatform, prevents our stream from even attempting to test out OBSMP.  We have a number of custom made Browser Source widgets, as well as a tablet-based scene switcher, all that require the WebSocket connections with OBSRemote.  Our Follower Widget, for example, uses OBSRemote to validate if it is or is not in the current scene, to determine if it should play the alert sound or animation.  The widget has to be global to prevent reloading each time a scene changes.

**Comment by asquelt** [comment]
neccessary API has been introduced in studio code: https://github.com/jp9000/obs-studio/commit/8836592d92284c454f2e2d00b512837d9c53cbe9

**Comment by asquelt** [comment]
there is studio implementation: https://github.com/Palakis/obs-websocket/
maybe you should merge it.
