### ISSUE TITLE
OBSApi.h

### ISSUE THREAD

**Issue by sKeLeTr0n** [bilhamil/OBSRemote#2]
Hey there,

can you tell me where I can get the OBSApi.h from? I want to make my own plugin and wanted to compile yours as a reference.

Thank you very much!

sKeLeTr0n

**Comment by bilhamil** [comment]
Hi there,
   My project is setup to compile against a checked out copy of obs. If you would like to compile it you should check out the Auth branch of my project. And in the same folder checkout the master branch of the OBS project. OBSApi.h is in that project.

Hope this helps!

Best,
Bill

**Comment by sKeLeTr0n** [comment]
I must be blind, I dont see OBSApi.h anywhere :/

**Comment by bilhamil** [comment]
https://github.com/jp9000/OBS/blob/master/OBSApi/OBSApi.h
